CREATE TABLE CLIENTE(
  ID_CLIENTE NUMBER(8) CONSTRAINT CLIENTE_PK PRIMARY KEY,
  NOMBRE VARCHAR(50) CONSTRAINT NOM_CLI_NN NOT NULL
);

INSERT INTO CLIENTE VALUES(1,'JUAN');
INSERT INTO CLIENTE VALUES(2,'PEDRO');

CREATE TABLE PRODUCTO(
  ID_PRODUCTO NUMBER(8) CONSTRAINT PRODUCTO_PK PRIMARY KEY,
  NOMBRE VARCHAR(50) CONSTRAINT NOM_PRO_NN NOT NULL,
  DESCRIPCION VARCHAR(150),
  CANTIDAD NUMBER(5) CONSTRAINT CAN_PRO_NN NOT NULL,
  PRECIO NUMBER(7,2) CONSTRAINT PRE_PRO_NN NOT NULL
);

INSERT INTO PRODUCTO VALUES(1,'COCA-COLA','SODA',100,10.50);
INSERT INTO PRODUCTO VALUES(2,'DORITOS','FRITURAS',200,11.50);

CREATE TABLE PROVEEDOR(
  ID_PROVEEDOR NUMBER(5) CONSTRAINT PROVEEDOR_PK PRIMARY KEY,
  NOMBRE VARCHAR(50) CONSTRAINT NOM_PROV_NN NOT NULL
);

INSERT INTO PROVEEDOR VALUES(1,'COCA-COLA');
INSERT INTO PROVEEDOR VALUES(2,'SABRITAS');

CREATE TABLE COMPRA(
  ID_CLIENTE NUMBER(8),
  ID_PRODUCTO NUMBER(8),
  FECHA DATE,
  CONSTRAINT COMPRA_PK PRIMARY KEY(ID_CLIENTE,ID_PRODUCTO,FECHA),
  CONSTRAINT CLI_COM_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  CONSTRAINT PRO_COM_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

INSERT INTO COMPRA VALUES(1,1,'10/10/19');
INSERT INTO COMPRA VALUES(2,2,'11/11/29');

CREATE TABLE RESURTIR(
  ID_PRODUCTO NUMBER(8),
  ID_PROVEEDOR NUMBER(5),
  FECHA DATE,
  CANTIDAD NUMBER(5) CONSTRAINT CAN_RES_NN NOT NULL,
  CONSTRAINT RESURTIR_PK PRIMARY KEY (ID_PRODUCTO,ID_PROVEEDOR,FECHA),
  CONSTRAINT PRO_RES_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
  CONSTRAINT PROV_RES_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);

INSERT INTO RESURTIR VALUES(1,1,1,'30/04/21');
INSERT INTO RESURTIR VALUES(1,1,1,'08/01/20');

SELECT * FROM RESURTIR;
COMMIT;