a) El listado de los clientes y sus autos.
SELECT CL.ID_CLIENTE || ' ' || CL.NOMBRE || ' ' || CL.APATERNO || ' ' || CL.AMATERNO AS CLIENTE,
AU.MATRICULA || ' ' || AU.MARCA || ' ' || AU.MODELO AS AUTOMOVIL
FROM CLIENTE CL, AUTOMOVIL AU, PERTENECE P 
WHERE CL.ID_CLIENTE = P.ID_CLIENTE AND AU.MATRICULA = P.MATRICULA;


b. El listado de todos los autos que han sido revisados.
SELECT AU.MATRICULA || ' ' || AU.MARCA || ' ' || AU.MODELO || ' ' || AU.COLOR AS REVISADOS
FROM AUTOMOVIL AU, REPARACION R WHERE AU.MATRICULA = R.MATRICULA;


c. El listado de las revisiones de un auto en particular, incluyendo los consumibles usados en dicha revisión.
SELECT R.ID_REVISION, R.FECHA_REP, R.ID_CLIENTE, R.MATRICULA, CO.ID_COMBUSTIBLE, CO.NOMBRE_COM, CO.PRECIO, CO.CANTIDAD
FROM REPARACION R, COMBUSTIBLE CO WHERE CO.ID_COMBUSTIBLE = R.ID_COMBUSTIBLE AND R.MATRICULA = '63SDF352';


d. El listado de los consumibles que se han usado en reparaciones.
SELECT CO.ID_COMBUSTIBLE, CO.NOMBRE_COM, CO.PRECIO, CO.CANTIDAD FROM COMBUSTIBLE CO, REPARACION R
WHERE CO.ID_COMBUSTIBLE = R.ID_COMBUSTIBLE;


e. El listado de consumibles que nunca han sido utilizados en alguna reparación.
INSERT INTO COMBUSTIBLE VALUES(3,'ACEITE VOLANTE',123.45,150);
INSERT INTO COMBUSTIBLE VALUES(4,'ADITIVO',123.45,150);

SELECT ID_COMBUSTIBLE,NOMBRE_COM,PRECIO,CANTIDAD FROM COMBUSTIBLE WHERE ID_COMBUSTIBLE NOT IN(SELECT ID_COMBUSTIBLE FROM REPARACION); 

SELECT * FROM COMBUSTIBLE;


INSERT INTO CLIENTE VALUES(3,'Pérez','Aguirre','Juan',6475638920);
SELECT * FROM CLIENTE;
INSERT INTO AUTOMOVIL VALUES('36DHV463','HONDA','ACCORD','GRIS');
INSERT INTO PERTENECE VALUES(3,'36DHV463','05/05/20');
SELECT * FROM REPARACION;
INSERT INTO REPARACION VALUES(3,'07/05/20',1,1,3,'36DHV463','05/05/20');
INSERT INTO REPARACION VALUES(4,'07/05/20',2,2,3,'36DHV463','05/05/20');
f. Los clientes que han visitado el taller.
SELECT * FROM CLIENTE;


g. El número de veces que Juan Pérez ha visitado el taller.
SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE = 'Juan' AND APATERNO = 'Pérez';

SELECT COUNT(ID_CLIENTE) AS VECES FROM REPARACION
WHERE ID_CLIENTE = ANY(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE = 'Juan' AND APATERNO = 'Pérez');


h. El número de revisiones hechas en una fecha dada por el usuario.
SELECT COUNT(FECHA_REP) AS NUM_REVISIONES FROM REPARACION WHERE FECHA_REP = '07/05/20';
SELECT * FROM REPARACION;


i. Los costos de los consumibles usados en las revisiones de un vehiculo dado.
SELECT NOMBRE_COM,PRECIO FROM COMBUSTIBLE WHERE ID_COMBUSTIBLE = ANY(SELECT ID_COMBUSTIBLE FROM REPARACION WHERE MATRICULA = '36DHV463');


j. El listado de precios de los consumibles dentro del taller (asumiendo que se tiene una mini refaccionaria).
SELECT NOMBRE_COM,PRECIO FROM COMBUSTIBLE;




COMMIT;
