--a. Indicar todas las competiciones existentes en el último mes.


--b. Indicar los patrocinadores más recurrentes.
SELECT * FROM LIST_OF_SPONSORS WHERE SPONSOR_ID IN (SELECT SPONSOR_ID FROM 
(SELECT SPONSOR_ID,COUNT(*) AS CONT FROM ACTUAL_TOURNAMENT_SPONSORS GROUP BY SPONSOR_ID)TMP 
WHERE TMP.CONT = (SELECT MAX(CONT) FROM (SELECT SPONSOR_ID,COUNT(*) AS CONT FROM ACTUAL_TOURNAMENT_SPONSORS GROUP BY SPONSOR_ID)TMP));

--c. Indicar los jugadores que más han participado en torneos.
SELECT * FROM PLAYERS WHERE PLAYER_ID IN (SELECT PLAYER_ID FROM 
(SELECT PLAYER_ID,COUNT(*) AS CONT FROM PLAYER_TOURNAMENT_PARTI GROUP BY PLAYER_ID)TMP 
WHERE TMP.CONT = (SELECT MAX(CONT) FROM (SELECT PLAYER_ID,COUNT(*) AS CONT FROM PLAYER_TOURNAMENT_PARTI GROUP BY PLAYER_ID)TMP));

--d. Indicar el jugador que más ha ganado.
SELECT * FROM MATCHES;
SELECT * FROM REF_RESULT_CODES;

SELECT * FROM PLAYERS WHERE PLAYER_ID = (SELECT PLAYER_ID_1 FROM 
(SELECT PLAYER_ID_1,RESULT_CODE,COUNT(*) AS TOTAL FROM MATCHES GROUP BY PLAYER_ID_1,RESULT_CODE)TMP 
WHERE TMP.TOTAL = (SELECT MAX(TOTAL) FROM (SELECT PLAYER_ID_1,RESULT_CODE,COUNT(*) AS TOTAL FROM MATCHES GROUP BY PLAYER_ID_1,RESULT_CODE)) 
AND TMP.RESULT_CODE = 1);

--e. Indicar el rango del jugador que más ha ganado.


--f. Indicar el club de cada jugador que ha participado en cada competición del último año.
SELECT * FROM TOURNAMENTS;
SELECT CC.*,P.* FROM CHESS_CLUBS CC JOIN PLAYERS P ON CC.CLUB_ID = P.CLUB_ID
JOIN PLAYER_TOURNAMENT_PARTI PTP ON PTP.PLAYER_ID = P.PLAYER_ID
JOIN TOURNAMENTS T ON T.TOURNAMENT_ID = PTP.TOURNAMENT_ID AND TO_CHAR(T.TOURNAMENT_START_DATE,'YY') = '15';

--g. Indicar el encuentro que más ha durado.


--h. Indicar el patrocinador que no ha participado en un torneo.
SELECT * FROM LIST_OF_SPONSORS WHERE SPONSOR_ID NOT IN (SELECT SPONSOR_ID FROM ACTUAL_TOURNAMENT_SPONSORS);
